services:
  authwall:
    image: vbarbarosh/authwall
    restart: unless-stopped
    environment:
      AUTHWALL_UPSTREAM_URL: http://notes:3000
      AUTHWALL_SEED: foo:foo
    ports:
      - 3000:3000
    volumes:
      - ./data-authwall:/app/data

  notes:
    image: vbarbarosh/notes
    restart: unless-stopped
    volumes:
      - ./data-notes:/app/data
